/*
    VEHICLE_TYPE = What type the vehicle is.
        types : ['AA', 'APC', 'ARMEDCAR', 'ARTILLERY', 'BOAT', 'HELI', 'PLANE', 'STATICAA', 'STATICAT', 'STATICMG', 'STATICMORTAR', 'TANK', 'UAV', 'UNARMEDCAR']

    VEHICLE_CONDITION = Condition to show.
        VEHICLE_CONDITION_X : VEHICLE_CONDITION + VEHICLE_TYPE

    VEHICLE_CONDITION_X can also be replaced with a string to add your own condition.

    ITEM(CLASSNAME, PRICE, VEHICLE_TYPE, VEHICLE_CONDITION_X);
*/

class my_extension_vehicles_TCP : vehicles_base
{
    ITEM(TCP_B_UNSC_A_M12A, 0, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);
    ITEM(TCP_B_UNSC_A_M12A_LAAG_M41, 0, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(TCP_B_UNSC_A_M12A_ALIM_M68, 100, ARMEDCAR, VEHICLE_CONDITION_ARMEDCAR);
    ITEM(TCP_B_UNSC_A_M831A, 0, UNARMEDCAR, VEHICLE_CONDITION_UNARMEDCAR);

    ITEM(TCP_B_UNSC_A_LAAG_M41, 0, STATICMG, VEHICLE_CONDITION_STATICMG);
    ITEM(TCP_B_UNSC_A_ALIM_M68, 100, STATICAT, VEHICLE_CONDITION_STATICAT);
};